base/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.home, name='home'),
	path('posts/', views.posts, name='posts'),
	path('post/<slug:slug>', views.post, name='post'),
	path('profile/', views.profile, name='profile'),

	# CRUD PATHS

	path('create_post/', views.createPost, name='create_post'),
	path('update_post/<slug:slug>', views.updatePost, name='update_post'),
	path('delete_post/<slug:slug>', views.deletePost, name='delete_post'),

	path('send_email/', views.sendEmail, name='send_email'),

]

chinyereunamba/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf  import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

base/models.py
from django.db import models		
from django.utils.text import slugify

from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.

class Tag(models.Model):
	name = models.CharField(max_length=200)


	def __str__(self):
		return self.name

class Post(models.Model):
	headline = models.CharField(max_length=200)
	sub_headline = models.CharField(max_length=200, null=True, blank=True)
	thumbnail = models.ImageField(null=True,blank=True, upload_to="images", default='placeholder.jpg')
	body = RichTextUploadingField(null=True, blank=True)
	created = models.DateTimeField(auto_now_add=True)
	active = models.BooleanField(default=False)
	featured = models.BooleanField(default=False)
	tags = models.ManyToManyField(Tag)
	slug = models.SlugField(null=True, blank=True)

	def __str__(self):
		return self.headline

	def save(self, *args, **kwargs):
		if self.slug == None:
			slug = slugify(self.headline)

			has_slug = Post.objects.filter(slug=slug).exists()
			count  = 1
			while has_slug:
				count += 1
				slug = slugify(self.headline) + '-' + str(count)
				has_slug = Post.objects.filter(slug=slug).exists()

			self.slug = slug

		super().save(*args, **kwargs)

base/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.core.mail import EmailMessage
from django.conf import settings
from django.template.loader import render_to_string

from .models import Post 
from .form import PostForm
from .filters import PostFilter

# Create your views here.


def home(request):
	posts = Post.objects.filter(active=True, featured=True)[0:3]

	context = {'posts':posts}
	return render(request, 'base/index.html', context)

def posts(request):
	posts = Post.objects.filter(active=True)
	myfilter = PostFilter(request.GET, queryset=posts)
	posts = myfilter.qs

	page = request.GET.get('page')
	paginator = Paginator(posts, 3)

	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		posts = paginator.page(1)
	except EmptyPage:
		posts = paginator.page(paginator.num_pages)


	context = {'posts':posts, 'myfilter':myfilter}

	return render(request, 'base/posts.html', context)

def post(request, slug):
	post = Post.objects.get(slug=slug)

	context = {'post':post}
	return render(request, 'base/post.html',context)

def profile(request):
	return render(request, 'base/profile.html')


# CRUD VIEWS create delete and update

@login_required(login_url='home')
def createPost(request):
	form = PostForm()

	if request.method == "POST":
		form = PostForm(request.POST, request.FILES)
		if form.is_valid():
			
			form.save()

		return redirect('posts')

	context = {'form':form}
	return render(request, 'base/post_form.html', context)

@login_required(login_url='home')
def updatePost(request, slug):
	post = Post.objects.get(slug=slug)
	form = PostForm(instance=post)

	if request.method == "POST":
		form = PostForm(request.POST, request.FILES, instance=post)
		if form.is_valid():
			form.save()

		return redirect('posts')

	context = {'form':form}
	return render(request, 'base/post_form.html', context)


@login_required(login_url='home')
def deletePost(request, slug):
	post = Post.objects.get(slug=slug)

	if request.method == 'POST':
		post.delete()
		return redirect('posts')

	context = {'item':post}
	return render(request, 'base/delete.html', context)


def sendEmail(request):

	if request.method == "POST":
		template = render_to_string('base/email_template.html',{
			'name':request.POST['name'],
			'email':request.POST['email'],
			'message':request.POST['message'],
			})
		email = EmailMessage(
			request.POST['subject'],
			template,
			settings.EMAIL_HOST_USER,
			['chinyereunamba17@gmail.com']
			)

		email.fail_silently = False
		email.send()
	return render(request, 'base/email_sent.html')

base/templates/base/delete.html
{% extends 'base/main.html' %}

{% load static %}

{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="
{% static 'js/bootstrap.min.js' %}">

<div class="main-container">
	<form method="POST" action="">
		{% csrf_token %}
		<p>Are you sure you want to delete this {{item}}</p>
		<span>
			<input class="btn btn-danger" type="submit" value="Confirm">
			<button class="btn btn-success"><a href="{% url 'posts' %}" >Take me back</a></button>
		</span>


	</form>
</div>


{% endblock %}

base/templates/base/email_sent.html
{% extends 'base/main.html' %}

{% load static %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="
{% static 'js/bootstrap.min.js' %}">

<style type="text/css">
	html, body{
		height: 100%;
	}
	#page-wrapper{
		height: 100%;
		display: flex;
		justify-content: center;
		align-items: center;
		text-align: center;
		background-color: #eaeaea;
	}
	#success-box{
		max-width: 800px;
		height: auto;
		background-color: #fff;
		border: 1px solid #888;
		border-radius: 5px;
		padding: 5px;
	}
	#success-box p{
		font-size: 18px;
	}
</style>

<div id="page-wrapper">
	<div id="success-box" class="content-block">
		<h1>Thanks for reaching out!</h1>
		<p>Your message was successfully sent. I will do my  best to get back to you in a timely manner :)</p>
		<a id="back-btn" class="btn btn-success" href="{% url 'home' %}">BACK TO HOME PAGE</a>
	</div>
</div>

{% endblock %}

base/templates/base/email_template.html
{{message}}

{{name}}

{{email}}

base/templates/base/games.html
<!DOCTYPE html>
<html>
<head>
	<title>Portfolio</title>
	<meta name="viewport" content="width-device, initial-scale=1, maximum-scale=1, minimum-scale=1" charset="utf-8">
	<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Lato:100,300,400">
	<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:100,300,400">
	<link rel="stylesheet" type="text/css" href="default.css">
</head>

<body>
	<div class="nav-wrapper">
		<div class="dots-wrapper">
			<div id="dot-1" class="browser-dot"></div>			
			<div id="dot-2" class="browser-dot"></div>			
			<div id="dot-3" class="browser-dot"></div>		
		</div>

		<ul id="navigation">
			<li><a href="index.html">Home</a></li>
			<li><a href="">Contact</a></li>
		</ul>
	</div>

	<div class="main-container">

		<h3>Making Games With Python and Pygame</h3>

		<p>My Journey into Python has been wonderful. I discovered new things everyday as I learnt Python Programming Language.</p>

		<p>So, as practice I made two-dimensional game with Python's game development package - <strong>Pygame</strong>. It wasn't an easy task when I began, but I then realized everything can't be learnt in a day.</p>

		<p>My first real game which called "Jumpin' Plats" was the most frustating. But in the end I completed the game.</p>
		<h4>Screenshots</h4>

		<span class="images">
			<img src="images/show screen.png">
			<img src="images/play screen.png">
			<img src="images/end screen.png">
		</span>
		<p>The game can be downloaded from the link below</p>

		<p><a href="Game">Download Jumpin' Plats game</a></p>
	</div>
</body>
</html>

base/templates/base/home.html
{% extends 'base/main.html' %}

{% block content %}

<h1>Home Page</h1>

{% endblock %}

base/templates/base/index.html
{% load static %}

<!DOCTYPE html>
<html>
<head></head>
<body>
	<section class="s1">
		<div class="main-container">
			<div class="greeting-wrapper">
				<h1>Hi, I'm Chinyere Unamba</h1>
			</div>
			<div class="intro-wrapper">

					{% include 'base/main.html' %}

				<div class="left-column">
					<img id="profile_pic" src="{% static 'images/nobel.jpg' %}" alt="me">
					<h5 style="text-align: center; line-height: 0">Personalize Theme</h5>	
					<div id="theme-option-wrapper">
						<div data-mode="light" id="light-mode" class="theme-dot"></div>
						<div data-mode="blue" id="blue-mode" class="theme-dot"></div>
						<div data-mode="green" id="green-mode" class="theme-dot"></div>
						<div data-mode="purple"id="purple-mode" class="theme-dot"></div>
					</div>
					<p id="settings-note">*Theme settings will be saved for <br>your next visit</p>
				</div>	
				<div class="right-column">
					<div id="preview-shadow">
						<div id="preview">
							<div id="corner-tl" class="corner"></div>
							<div id="corner-tr" class="corner"></div>
							<h3>What I Do</h3>
							<p>I'm a <b>Full Stack Web Developer</b> working with <b>Django</b> as a backend framework.</p>
							<div id="corner-br" class="corner"></div>
							<div id="corner-bl" class="corner"></div>

						</div>
					</div>
					
				</div>
			</div>
		</div>
	</section>
	<section class="s2">
		<div class="main-container">
			<div class="about-wrapper">
				<div class="about-me" id="about-me">
					<h4>More about me</h4>
					<p>I'm Chinyere Unamba. An upcoming full stack developer. I do know Python, JavaScript and Django for backend development.</p>
					<p>consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
							
				
					<hr>
					<h4>Top Expertise</h4>
					<p>Fullstack developer with primary focus on Django: <a target="_blank" href="{% static 'resume.pdf' %}">Download Resume</a></p>

					<div id="skills">
						<ul>
							<li>Python</li>
							<li>Django</li>
							<li>JavaScript</li>
						</ul>

						<ul>
							<li>HTML5</li>
							<li>CSS3</li>
							<li>React</li>
						</ul>
					</div>
				</div>
				<div class="social-links">
					<img id="social_img" src="{% static 'images/image4.jpg' %}">
					<h3>Find me on Sololearn & Stack Overflow</h3>

					<p>Sololearn: <a target="_blank" href="#">Chinyere Unamba</a></p>
					<p>StackOverFlow: <a target="_blank" href="#">Chinyere Unamba</a></p>
				</div>
			</div>	
		</div>
	</section>

	<section class="s1">
		<div class="main-container">
			<h3 style="text-align: center;">Some of my past projects</h3>
			<div class="post-wrapper">
				{% for post in posts %}
				<div>
					
					<div class="post">
						<img class="thumbnail" src="{{post.thumbnail.url}}">
						<div class="post-preview">
							<h4 class="post-title">{{post.headline}}</h4>
							<p class="post-intro">{{post.sub_headline}}</p>
							<a href="{% url 'post' post.slug %}">Read More</a>
							<div>
								<hr>
								{% for tag in post.tags.all %}
									<span class="tag">{{tag}}</span>
								{% endfor %}
								<hr>
							</div>
						</div>
					</div>
					
				</div>
				{% endfor %}
				
				
				
			</div>
			<p align="center">
				<a href="{% url 'posts' %}">View More</a>
			</p>
			
			
		</div>
	</section>

	<section class="s2">
		<div class="main-container">
			<a href=""></a>
			<h3 style="text-align: center;">Get In Touch</h3>

			<form id="contact-form" method="POST" action="{% url 'send_email' %}">
				{% csrf_token %}

				<a name="contact"></a>

				<label>Name</label>
				<input class="input-field" type="text" name="name">

				<label>Subject</label>
				<input class="input-field" type="text" name="subject">

				<label>Email</label>
				<input class="input-field" type="email" name="email">

				<label>Message</label>
				<textarea class="input-field" type="text" name="subject"></textarea>

				<input id="submit-btn" type="submit" name="" value="Send">
			</form>
		</div>
	</section>

	<script type="text/javascript">
		let static = "{% static 'css' %}"	
	</script>
	<script type="text/javascript" src="{% static 'js/script.js' %}"></script>

	<section class="s1">
		<div class="main-container">
			<div class="footer">
			<small>Copyright &copy Chinyere Unamba 2020</small>
			</div>
		</div>
	</section>
</body>
</html>

base/templates/base/main.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Chinyere Unamba</title>
	<meta name="viewport" content="width-device, initial-scale=1, maximum-scale=1, minimum-scale=1" charset="utf-8">
	<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Lato:100,300,400">
	<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:100,300,400">
	
	<link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}">
	<link id="theme-style" rel="stylesheet" type="text/css" href="">
</head>
<body>

	{% include 'base/navbar.html' %}

	{% block content %}
	<!-- Content Goes here -->
	{% endblock %}
</body>
</html>

base/templates/base/navbar.html
<div class="nav-wrapper">

	<a href="{% url 'home' %}">
		<div class="dots-wrapper">
			<div id="dot-1" class="browser-dot"></div>			
			<div id="dot-2" class="browser-dot"></div>			
			<div id="dot-3" class="browser-dot"></div>		
		</div>
	</a>
	

	<ul id="navigation">
		<li><a href="{% url 'home' %}#aboutme">Home</a></li>
		<li><a href="{% url 'home' %}#contact-form">Contact</a></li>
		{% if request.user.is_authenticated %}
		<li><a href="{url 'create_post'}"></a></li>
		{% endif %}
	</ul>

</div>

base/templates/base/post.html
{% extends 'base/main.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="
{% static 'js/bootstrap.min.js' %}">
<div class="main-container">

<style type="text/css">
	img{
		max-width: 100%;
		object-fit: cover;
	}
</style>

<div class="main-container">
	<div class="post-wrapper">
		<div class="headline">
			<h1>{{post.headline}}</h1>
		</div>
		<div class="img">
			<img src="{{post.thumbnail.url}}">
		</div>
		
		<h4>{{post.sub_headline}}</h4>

		<p>{{post.body|safe}}</p>
	</div>
</div>

{% endblock %}

base/templates/base/post_form.html
{% extends 'base/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="
{% static 'js/bootstrap.min.js' %}">

<style type="text/css">
	#div_id_tags > div{
		max-height: 100px;
		overflow-y: scroll;
		border: 1px solid #888;
		padding: 5px;
		border-radius: 5px;
	}
	.form-check-input{
		margin-left: 5px;
	}
</style>

<div class="main-container">
	<h3>Post Form</h3>

<form action="" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{{form.media}}
		{{form|crispy}}

		<input class="btn btn-primary" type="submit" value="Submit Post">
	</form>
	<br>
</div>


{% endblock %}

base/templates/base/posts.html
{% extends 'base/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'js/bootstrap.min.js' %}">


<style type="text/css">
	#id_tags{
		max-height: 100px;
		overflow-y: scroll;
		border: 1px solid #888;
		border-radius: 5px;
		padding: 5px;
	}
	.btn{
		text-transform: uppercase;
	}
</style>

<div class="main-container">
	<h1>Posts</h1>

	<form id="searchForm" method="GET">
		{{myfilter.form|crispy}}
		<input class="btn btn-primary" type="submit" value="search">
	</form>

	<div class="post-wrapper">

		{% for post in posts %}
		<div>
			<div class="post">
				<img class="thumbnail" src="{{post.thumbnail.url}}">
				<div class="post-preview">
					<h4 class="post-title">{{post.headline}}</h4>
					<p class="post-intro">{{post.sub_headline}}</p>
					<a href="{% url 'post' post.slug %}">Read more</a>

					{% if request.user.is_authenticated %}
						| <a href="{% url 'update_post' post.slug %}">Edit</a>
						| <a href="{% url 'delete_post' post.slug %}">Delete</a>
					{% endif %}

					<hr>
					{% for tag in post.tags.all %}
						<span class="tag">{{tag}}</span>
					{% endfor %}
					<hr>
				</div>
			</div>
		</div>
			{% empty %}
				<h3>No post found...</h3>
		{% endfor %}
			
		
	</div>

	<div class="row">


		{% if posts.has_other_pages %}
			<ul class="pagination">

				{% if posts.has_previous %}
					<li class="page-item"><a data-page="{{posts.previous_page_number}}" class="page-link" href="?page={{posts.previous_page_number}}">&laquo</a></li>

					<li class="page-item"><a class="active page-link" href="?page=1">First</a></li>
				{% endif %}

				{% for i in posts.paginator.page_range %}
					{% if posts.number == i %}
						<li class="page-item"><a class="active page-link" href="">{{i}}</a></li>
					{% else %}
						<li class="page-item"><a data-page="{{i}}" class="page-link" href="?page={{i}}">{{i}}</a></li>
					{% endif %}
				{% endfor %}

				{% if posts.has_next %}
					<li class="page-item"><a data-page="{{posts.paginator.num_pagesr}}" class="page-link" href="?page={{posts.paginator.num_pages}}">Last</a></li>

					<li class="page-item"><a data-page="{{posts.next_page_number}}" class="page-link" href="?page={{posts.next_page_number}}">&raquo</a></li>
				{% endif %}
			</ul>
		{% endif %}
	</div>
</div>

<script type="text/javascript">
	let searchForm = document.getElementById('searchForm');
	let pageLinks = document.getElementByClassName('page-link');

	for (var  i=0; pageLinks.length; i++){
		pageLinks[i].addEventListener('click', function(e){
			e.preventDefault()
			let page = this.dataset.pageLinks
			console.log("Page:", page)
			searchForm.innerHTML += `<input value="$(page)" name="page" hidden>`
			searchForm.submit()
		})
	}
</script>

{% endblock %}

base/templates/base/profile.html
{% extends 'base/main.html' %}

{% block content %}

<h1>Profile</h1>

{% endblock %}